FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends strace && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -m -u 1000 sandboxuser

WORKDIR /code

USER sandboxuser